"""agnes-simple-ui local server.

Serves the single-page UI (static/) and one custom endpoint the Agnes
backend doesn't have: compositing a title onto a generated cover image
(Arabic-aware text shaping + RTL layout). Everything else the UI needs
(voices, task creation, progress, video/audio previews, plain image
generation) is called directly by the browser against the Agnes backend
on its own port -- this server does not proxy any of that.
"""
from __future__ import annotations

import io
import json
import os
import re
import subprocess
import time
import uuid

from flask import Flask, Response, jsonify, request, send_from_directory
from PIL import Image, ImageDraw, ImageFont

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, "static")
FONT_AR = os.path.join(BASE_DIR, "resource", "NotoNaskhArabicUI.ttf")
FONT_EN = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
PORT = int(os.environ.get("SIMPLE_UI_PORT", "8787"))

# Only ever allowed to reveal files generated by the Agnes backend itself --
# never an arbitrary path a client might send. This copy lives inside
# agnes-video-generator itself, so the backend is the parent directory.
AGNES_DIR = os.environ.get("AGNES_DIR", os.path.join(BASE_DIR, ".."))
WORKING_DIR_ROOT = os.path.realpath(os.path.join(AGNES_DIR, ".working_dir"))

# Projects: one JSON file per saved project, so a generation's settings (and
# the last task_id it produced) survive a page reload / server restart.
PROJECTS_DIR = os.path.join(BASE_DIR, "projects")
os.makedirs(PROJECTS_DIR, exist_ok=True)


def _project_path(project_id: str) -> str:
    # project_id is always our own uuid4 hex -- safe filename, no traversal risk.
    safe_id = re.sub(r"[^a-zA-Z0-9_-]", "", project_id)
    return os.path.join(PROJECTS_DIR, f"{safe_id}.json")

_ARABIC_RE = re.compile(r"[؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿]")


def _shape_text(text: str) -> str:
    """Arabic letter joining + bidi reorder; non-Arabic text passes through untouched.

    Mirrors agnes-video-generator's core/compositor/concatenator/concat.py
    `_shape_bidi_text`, since Pillow does not do complex text layout itself.
    """
    if not _ARABIC_RE.search(text):
        return text
    import arabic_reshaper
    from bidi.algorithm import get_display

    lines = text.split("\n")
    return "\n".join(get_display(arabic_reshaper.reshape(line)) for line in lines)


def _wrap_text(draw: "ImageDraw.ImageDraw", text: str, font: "ImageFont.FreeTypeFont", max_width: int) -> list:
    words = text.split(" ")
    lines: list = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if draw.textlength(candidate, font=font) <= max_width or not current:
            current = candidate
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def compose_cover(image_bytes: bytes, title_text: str, lang: str,
                   color: str = "white", position: str = "bottom") -> bytes:
    """Draw `title_text` on top of `image_bytes`, returning a new PNG's bytes."""
    img = Image.open(io.BytesIO(image_bytes)).convert("RGBA")
    width, height = img.size

    font_path = FONT_AR if lang == "ar" else FONT_EN
    font_size = max(int(width * 0.075), 28)
    font = ImageFont.truetype(font_path, font_size)

    draw = ImageDraw.Draw(img)
    max_text_width = int(width * 0.86)
    # Wrap on the raw (unshaped) text first -- shaping reorders characters for
    # display, so wrapping must happen before shaping or line breaks would land
    # in the wrong place. Each wrapped line is then shaped independently.
    raw_lines = _wrap_text(draw, title_text, font, max_text_width)
    lines = [_shape_text(line) for line in raw_lines]

    line_height = int(font_size * 1.3)
    block_height = line_height * len(lines) + 40

    # Bottom-safe-zone: stay clear of the very bottom strip YouTube's own
    # Shorts UI (progress bar / follow button) overlaps on thumbnails.
    bottom_margin = int(height * 0.14)
    if position == "top":
        block_top = int(height * 0.06)
    elif position == "center":
        block_top = (height - block_height) // 2
    else:  # bottom (default)
        block_top = height - bottom_margin - block_height

    # Semi-transparent backing bar for legibility over busy backgrounds.
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    overlay_draw = ImageDraw.Draw(overlay)
    overlay_draw.rectangle(
        [0, block_top - 16, width, block_top + block_height + 16],
        fill=(0, 0, 0, 120),
    )
    img = Image.alpha_composite(img, overlay)
    draw = ImageDraw.Draw(img)

    y = block_top
    for line in lines:
        line_width = draw.textlength(line, font=font)
        x = (width - line_width) / 2
        draw.text((x, y), line, font=font, fill=color,
                   stroke_width=max(font_size // 18, 2), stroke_fill="black")
        y += line_height

    out = io.BytesIO()
    img.convert("RGB").save(out, format="PNG")
    return out.getvalue()


app = Flask(__name__, static_folder=None)


@app.route("/")
def index():
    return send_from_directory(STATIC_DIR, "index.html")


@app.route("/<path:filename>")
def static_files(filename):
    return send_from_directory(STATIC_DIR, filename)


@app.route("/api/cover/compose", methods=["POST"])
def cover_compose():
    if "image" not in request.files:
        return jsonify({"ok": False, "error": "missing image file"}), 422
    title_text = request.form.get("title_text", "").strip()
    if not title_text:
        return jsonify({"ok": False, "error": "title_text is required"}), 422
    lang = request.form.get("lang", "ar")
    color = request.form.get("color", "white")
    position = request.form.get("position", "bottom")

    image_bytes = request.files["image"].read()
    try:
        png_bytes = compose_cover(image_bytes, title_text, lang, color, position)
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 500

    return Response(png_bytes, mimetype="image/png")


@app.route("/api/reveal-file", methods=["POST"])
def reveal_file():
    """Reveal a generated file in Finder. Restricted to Agnes's own working_dir."""
    data = request.get_json(silent=True) or {}
    path = data.get("path", "")
    if not path:
        return jsonify({"ok": False, "error": "missing path"}), 422

    real_path = os.path.realpath(path)
    if not real_path.startswith(WORKING_DIR_ROOT + os.sep):
        return jsonify({"ok": False, "error": "path not allowed"}), 403
    if not os.path.exists(real_path):
        return jsonify({"ok": False, "error": "file not found"}), 404

    try:
        subprocess.run(["open", "-R", real_path], check=True)
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 500
    return jsonify({"ok": True})


@app.route("/api/projects", methods=["GET"])
def list_projects():
    """List all saved projects, most recently updated first."""
    projects = []
    for filename in os.listdir(PROJECTS_DIR):
        if not filename.endswith(".json"):
            continue
        try:
            with open(os.path.join(PROJECTS_DIR, filename), "r", encoding="utf-8") as f:
                projects.append(json.load(f))
        except Exception:
            continue
    projects.sort(key=lambda p: p.get("updated_at", 0), reverse=True)
    return jsonify({"ok": True, "projects": projects})


@app.route("/api/projects", methods=["POST"])
def save_project():
    """Create (no id given) or update (id given) a project's saved state."""
    data = request.get_json(silent=True) or {}
    project_id = data.get("id") or uuid.uuid4().hex
    now = time.time()

    existing = {}
    if os.path.exists(_project_path(project_id)):
        try:
            with open(_project_path(project_id), "r", encoding="utf-8") as f:
                existing = json.load(f)
        except Exception:
            existing = {}

    project = {**existing, **data, "id": project_id, "updated_at": now}
    project.setdefault("created_at", now)

    with open(_project_path(project_id), "w", encoding="utf-8") as f:
        json.dump(project, f, ensure_ascii=False, indent=2)

    return jsonify({"ok": True, "project": project})


@app.route("/api/projects/<project_id>", methods=["GET"])
def get_project(project_id):
    path = _project_path(project_id)
    if not os.path.exists(path):
        return jsonify({"ok": False, "error": "project not found"}), 404
    with open(path, "r", encoding="utf-8") as f:
        return jsonify({"ok": True, "project": json.load(f)})


@app.route("/api/projects/<project_id>", methods=["DELETE"])
def delete_project(project_id):
    path = _project_path(project_id)
    if os.path.exists(path):
        os.remove(path)
    return jsonify({"ok": True})


def main():
    print(f"agnes-simple-ui running at http://localhost:{PORT}")
    app.run(host="127.0.0.1", port=PORT)


if __name__ == "__main__":
    main()
