"""core.compositor.watermark — 视频水印处理器

基于 ffmpeg drawtext 滤镜，在视频右下角叠加双行水印：
- 归属行 + 地址行（如 "Agnes Video Generator 生成 / video.lichuanyang.top"）
- 根据 prompt 语言自动选择中/英文
- 字号自适应视频分辨率
"""

import logging
import os
import re
import subprocess

logger = logging.getLogger(__name__)

# CJK 字符检测（覆盖中文）
_CJK_RE = re.compile(r'[\u4e00-\u9fff\u3400-\u4dbf\uf900-\ufaff]')

# 字体路径（项目内置）
_DEFAULT_FONT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "resource", "fonts", "STHeitiMedium.ttc",
)

# 水印文本模板
WATERMARK_TEXTS = {
    "zh": {
        "line1": "由 Agnes Video Generator 生成",
        "line2": "video.lichuanyang.top",
    },
    "en": {
        "line1": "Generated by Agnes Video Generator",
        "line2": "video.lichuanyang.top",
    },
}


def _compute_params(video_width: int, video_height: int) -> dict:
    """根据视频分辨率计算水印字号、边距等参数。

    字号依据视频高度自适应：
        font_size = max(12, round(video_height * 0.022))

    Returns:
        dict with font_size, url_font_size, boxborderw, right_margin, bottom_margin, line_spacing
    """
    font_size = max(12, round(video_height * 0.022))
    url_font_size = max(10, round(font_size * 0.85))
    boxborderw = max(4, round(font_size * 0.4))
    right_margin = max(16, round(video_width * 0.02))
    bottom_margin = max(12, round(video_height * 0.015))
    line_spacing = max(2, round(font_size * 0.15))
    return {
        "font_size": font_size,
        "url_font_size": url_font_size,
        "boxborderw": boxborderw,
        "right_margin": right_margin,
        "bottom_margin": bottom_margin,
        "line_spacing": line_spacing,
    }


def detect_language(text: str) -> str:
    """根据文本检测水印语言。

    Args:
        text: 用户输入的 prompt / idea / manuscript_text / script_text

    Returns:
        "zh" if CJK characters found, "en" otherwise
    """
    if not text:
        return "en"
    if _CJK_RE.search(text):
        return "zh"
    return "en"


def build_watermark_text(language: str) -> str:
    """构建双行水印文本。

    Args:
        language: "zh" | "en"

    Returns:
        ffmpeg drawtext 文本字符串（两行用 \\n 分隔）
    """
    texts = WATERMARK_TEXTS.get(language, WATERMARK_TEXTS["en"])
    return f"{texts['line1']}\\n{texts['line2']}"


def add_watermark(
    input_path: str,
    output_path: str,
    video_width: int,
    video_height: int,
    language: str = "en",
    font_path: str = _DEFAULT_FONT,
) -> bool:
    """使用 ffmpeg drawtext 在视频右下角叠加水印。

    Args:
        input_path: 输入视频路径
        output_path: 输出视频路径
        video_width: 视频宽度
        video_height: 视频高度
        language: 水印语言 "zh" | "en"
        font_path: 字体文件路径

    Returns:
        True on success, False on failure (不会抛异常)
    """
    if not os.path.exists(input_path):
        logger.error(f"[Watermark] Input not found: {input_path}")
        return False

    if not os.path.exists(font_path):
        logger.warning(f"[Watermark] Font not found: {font_path}, skipping watermark")
        # 字体缺失时，直接复制原文件（优雅降级）
        import shutil
        shutil.copy2(input_path, output_path)
        return False

    params = _compute_params(video_width, video_height)
    text = build_watermark_text(language)

    drawtext = (
        f"fontfile={font_path}:"
        f"text='{text}':"
        f"fontsize={params['font_size']}:"
        f"fontcolor=white@0.85:"
        f"box=1:boxcolor=black@0.35:boxborderw={params['boxborderw']}:"
        f"x=w-tw-{params['right_margin']}:"
        f"y=h-th-{params['bottom_margin']}:"
        f"shadowx=1:shadowy=1:shadowcolor=black@0.4:"
        f"line_spacing={params['line_spacing']}"
    )

    cmd = [
        "ffmpeg",
        "-y",
        "-i", input_path,
        "-vf", f"drawtext={drawtext}",
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "18",
        "-c:a", "copy",
        output_path,
    ]

    logger.info(f"[Watermark] Processing {os.path.basename(input_path)} "
                f"({video_width}x{video_height}, lang={language}, "
                f"fontsize={params['font_size']})")

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=300,
        )
        if result.returncode != 0:
            logger.error(f"[Watermark] ffmpeg failed: {result.stderr[:500]}")
            # 降级：复制原文件
            import shutil
            shutil.copy2(input_path, output_path)
            return False

        logger.info(f"[Watermark] Complete: {os.path.basename(output_path)}")
        return True
    except subprocess.TimeoutExpired:
        logger.error("[Watermark] ffmpeg timed out after 300s")
        import shutil
        shutil.copy2(input_path, output_path)
        return False
    except Exception as e:
        logger.error(f"[Watermark] Unexpected error: {e}")
        import shutil
        shutil.copy2(input_path, output_path)
        return False
